export type ProjectsTableData = {
    id: number,
    address: Address|string|null,
    icon: string,
    name: string,
    price: number,
    inWallet: number,
    walletValue: number,
    stakedNfts: number,
    unstakedNfts: number,
    totalNfts: number,
    rewardsRate: number,
    dailyRewardsRate: number,
    dailyWalletRewardsRate: number,
    rewards: number,
    rewardsValue: number,
}